### PR TITLE
Simplify deck builds with list operations.

### PR DESCRIPTION
**Pull request by barraponto**
Python provides list operations:

``` python
[1] + [1] = [1, 1]
[1] + [1] + [1] = [1, 1, 1]
3 * [1] = [1, 1, 1]
```

We can use that to build the decks.

### CODE REVIEW

**Comment by MarcoWorms** [comment]
Simply amazing :open_mouth:,thanks

**Comment by barraponto** [comment]
Recommended reading: http://openbookproject.net/thinkcs/python/english3e/tuples.html

**Comment by MarcoWorms** [comment]
So, what I got from that read is that basically a Tuple is an immutable Array. I googled "why use Tuple instead of Array" and got to the conclusion that I should use Tuple when doing immutable arrays simply because it's faster for Python to read them. Thanks again, this language never ceases to amaze me :D

**Comment by barraponto** [comment]
Actually, I wanted you to understand how `a, b = 1, 2` works. It's used in https://github.com/MarcoWorms/Weed-card-game/commit/49796f47d3f7c4161a50e986c6081d8194c4c232#diff-86afa4d6818202b7cafc3ef2a0cc023bR43

**Comment by MarcoWorms** [comment]
Yep, you used "cardname, amount" to get both dictionary "columns" in the same line. Really awesome :)

**Pull request merged**
